server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: springbootbackend

  mqtt:
    username: admin
    password: public
    url: tcp://47.97.42.12:1883
    subClientId: mqtt-client
    subTopic: testtopic/1/gas,testtopic/1/angle
    pubClientId: mqtt-client

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/engineer?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 170945

  # 邮件服务器配置
  mail:
    host: smtp.qq.com # QQ邮箱SMTP服务器
    port: 465
    username: 1489197981@qq.com # QQ邮箱账号
    password: jemibjpfvfjajbhh # 邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    default-encoding: UTF-8

  # Redis配置
  redis:
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器端口
    password: # Redis服务器密码（如果有）
    database: 0 # 使用的数据库索引
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1ms # 连接池最大阻塞等待时间
        max-idle: 8 # 连接池中最大空闲连接
        min-idle: 0 # 连接池中最小空闲连接
    timeout: 5000ms # 连接超时时间

# 阿里云短信服务配置
aliyun:
  sms:
    access-key-id: xxxxxxxx
    access-key-secret: xxxxxxxx
    region-id: cn-hangzhou

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yang.springbootbackend.domain
  configuration:
    # mybatis 配置
    # 驼峰转下划线（默认：false）
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)



# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yang.springbootbackend.controller

# 业务配置
app:
  business:
    verification-code:
      email-expire-minutes: 5
      sms-expire-minutes: 5
      image-expire-minutes: 3
      send-interval-seconds: 60
      max-attempts: 5
    session:
      expire-minutes: 30
      single-device-login: true
      login-cooldown-seconds: 300
    security:
      password-salt: "yang"
      enable-ip-limit: false
      ip-rate-limit: 100
    file-upload:
      max-size-mb: 10
      allowed-types: ["jpg", "jpeg", "png", "gif", "pdf", "doc", "docx"]
      upload-path: "/uploads"

